name: Blauhaus Packages
on:
  push:
    branches:
    - release/*

jobs:

  build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
     - name: Set Version
       run: |
        npm install @actions/core --save
        node ./scripts/getversion.js
     - name: Build NuGet Package
       run: |
        dotnet build ./src/Blauhaus.Common.sln --configuration Release
        dotnet pack ./src/Blauhaus.Common.ValueObjects/Blauhaus.Common.ValueObjects.csproj -p:PackageVersion=${VERSION_NAME} --no-build --output ./ --configuration Release 
        dotnet pack ./src/Blauhaus.Common.Config/Blauhaus.Common.Config.csproj -p:PackageVersion=${VERSION_NAME} --no-build --output ./ --configuration Release 
        dotnet pack ./src/Blauhaus.Common.TestHelpers/Blauhaus.Common.TestHelpers.csproj -p:PackageVersion=${VERSION_NAME} --no-build --output ./ --configuration Release 
        dotnet pack ./src/Blauhaus.Common.TestHelpers.Hotchocolate/Blauhaus.Common.TestHelpers.Hotchocolate.csproj -p:PackageVersion=${VERSION_NAME} --no-build --output ./ --configuration Release 
        dotnet pack ./src/Blauhaus.Common.TestHelpers.Http/Blauhaus.Common.TestHelpers.Http.csproj -p:PackageVersion=${VERSION_NAME} --no-build --output ./ --configuration Release 
        dotnet pack ./src/Blauhaus.Common.Time/Blauhaus.Common.Time.csproj -p:PackageVersion=${VERSION_NAME} --no-build --output ./ --configuration Release 
        dotnet pack ./src/Blauhaus.Common.Utils/Blauhaus.Common.Utils.csproj -p:PackageVersion=${VERSION_NAME} --no-build --output ./ --configuration Release 
        dotnet pack ./src/Blauhaus.Common.Domain/Blauhaus.Common.Domain.csproj -p:PackageVersion=${VERSION_NAME} --no-build --output ./ --configuration Release 
     - name: Deploy NuGet Package
       run:  |
        dotnet nuget push /home/runner/work/Blauhaus.Common/Blauhaus.Common/Blauhaus.Common.ValueObjects.${VERSION_NAME}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        dotnet nuget push /home/runner/work/Blauhaus.Common/Blauhaus.Common/Blauhaus.Common.Config.${VERSION_NAME}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        dotnet nuget push /home/runner/work/Blauhaus.Common/Blauhaus.Common/Blauhaus.Common.TestHelpers.${VERSION_NAME}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        dotnet nuget push /home/runner/work/Blauhaus.Common/Blauhaus.Common/Blauhaus.Common.TestHelpers.Hotchocolate.${VERSION_NAME}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        dotnet nuget push /home/runner/work/Blauhaus.Common/Blauhaus.Common/Blauhaus.Common.TestHelpers.Http.${VERSION_NAME}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        dotnet nuget push /home/runner/work/Blauhaus.Common/Blauhaus.Common/Blauhaus.Common.Time.${VERSION_NAME}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        dotnet nuget push /home/runner/work/Blauhaus.Common/Blauhaus.Common/Blauhaus.Common.Utils.${VERSION_NAME}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        dotnet nuget push /home/runner/work/Blauhaus.Common/Blauhaus.Common/Blauhaus.Common.Domain.${VERSION_NAME}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
